from app.models import db, environment, SCHEMA
from ..models.user import follows
from sqlalchemy.sql import text
from sqlalchemy import insert


# Adds a demo user, you can add other users here if you want
def seed_follows():
    friends_list = [
        {'following': 3, 'user_is': 2},
        {'following': 7, 'user_is': 2},
        {'following': 8, 'user_is': 2},
        {'following': 10, 'user_is': 2},
        {'following': 11, 'user_is': 2},
        {'following': 12, 'user_is': 2},
        {'following': 2, 'user_is': 3},
        {'following': 7, 'user_is': 3},
        {'following': 8, 'user_is': 3},
        {'following': 10, 'user_is': 3},
        {'following': 11, 'user_is': 3},
        {'following': 12, 'user_is': 3},
        {'following': 2, 'user_is': 7},
        {'following': 3, 'user_is': 7},
        {'following': 8, 'user_is': 7},
        {'following': 10, 'user_is': 7},
        {'following': 11, 'user_is': 7},
        {'following': 12, 'user_is': 7},
        {'following': 2, 'user_is': 8},
        {'following': 3, 'user_is': 8},
        {'following': 7, 'user_is': 8},
        {'following': 10, 'user_is': 8},
        {'following': 11, 'user_is': 8},
        {'following': 12, 'user_is': 8},
        {'following': 2, 'user_is': 10},
        {'following': 3, 'user_is': 10},
        {'following': 8, 'user_is': 10},
        {'following': 7, 'user_is': 10},
        {'following': 11, 'user_is': 10},
        {'following': 12, 'user_is': 10},
        {'following': 2, 'user_is': 11},
        {'following': 3, 'user_is': 11},
        {'following': 8, 'user_is': 11},
        {'following': 10, 'user_is': 11},
        {'following': 7, 'user_is': 11},
        {'following': 12, 'user_is': 11},
        {'following': 2, 'user_is': 12},
        {'following': 3, 'user_is': 12},
        {'following': 8, 'user_is': 12},
        {'following': 10, 'user_is': 12},
        {'following': 11, 'user_is': 12},
        {'following': 7, 'user_is': 12},
        {'following': 5, 'user_is': 1},
        {'following': 6, 'user_is': 1},
        {'following': 9, 'user_is': 1},
        {'following': 13, 'user_is': 1},
        {'following': 14, 'user_is': 1},
        {'following': 15, 'user_is': 1},
        {'following': 16, 'user_is': 1},
        {'following': 17, 'user_is': 1},
        {'following': 1, 'user_is': 4},
        {'following': 5, 'user_is': 4},
        {'following': 6, 'user_is': 4},
        {'following': 9, 'user_is': 4},
        {'following': 13, 'user_is': 4},
        {'following': 14, 'user_is': 4},
        {'following': 15, 'user_is': 4},
        {'following': 16, 'user_is': 4},
        {'following': 17, 'user_is': 4},
        {'following': 4, 'user_is': 5},
        {'following': 1, 'user_is': 5},
        {'following': 6, 'user_is': 5},
        {'following': 9, 'user_is': 5},
        {'following': 13, 'user_is': 5},
        {'following': 14, 'user_is': 5},
        {'following': 15, 'user_is': 5},
        {'following': 16, 'user_is': 5},
        {'following': 17, 'user_is': 5},
        {'following': 4, 'user_is': 6},
        {'following': 5, 'user_is': 6},
        {'following': 1, 'user_is': 6},
        {'following': 9, 'user_is': 6},
        {'following': 13, 'user_is': 6},
        {'following': 14, 'user_is': 6},
        {'following': 15, 'user_is': 6},
        {'following': 16, 'user_is': 6},
        {'following': 17, 'user_is': 6},
        {'following': 4, 'user_is': 9},
        {'following': 5, 'user_is': 9},
        {'following': 6, 'user_is': 9},
        {'following': 1, 'user_is': 9},
        {'following': 13, 'user_is': 9},
        {'following': 14, 'user_is': 9},
        {'following': 15, 'user_is': 9},
        {'following': 16, 'user_is': 9},
        {'following': 17, 'user_is': 9},
        {'following': 4, 'user_is': 13},
        {'following': 5, 'user_is': 13},
        {'following': 6, 'user_is': 13},
        {'following': 9, 'user_is': 13},
        {'following': 1, 'user_is': 13},
        {'following': 14, 'user_is': 13},
        {'following': 15, 'user_is': 13},
        {'following': 16, 'user_is': 13},
        {'following': 17, 'user_is': 13},
        {'following': 4, 'user_is': 14},
        {'following': 5, 'user_is': 14},
        {'following': 6, 'user_is': 14},
        {'following': 9, 'user_is': 14},
        {'following': 13, 'user_is': 14},
        {'following': 1, 'user_is': 14},
        {'following': 15, 'user_is': 14},
        {'following': 16, 'user_is': 14},
        {'following': 17, 'user_is': 14},
        {'following': 4, 'user_is': 15},
        {'following': 5, 'user_is': 15},
        {'following': 6, 'user_is': 15},
        {'following': 9, 'user_is': 15},
        {'following': 13, 'user_is': 15},
        {'following': 14, 'user_is': 15},
        {'following': 1, 'user_is': 15},
        {'following': 16, 'user_is': 15},
        {'following': 17, 'user_is': 15},
        {'following': 4, 'user_is': 16},
        {'following': 5, 'user_is': 16},
        {'following': 6, 'user_is': 16},
        {'following': 9, 'user_is': 16},
        {'following': 13, 'user_is': 16},
        {'following': 14, 'user_is': 16},
        {'following': 15, 'user_is': 16},
        {'following': 1, 'user_is': 16},
        {'following': 17, 'user_is': 16},
        {'following': 4, 'user_is': 17},
        {'following': 5, 'user_is': 17},
        {'following': 6, 'user_is': 17},
        {'following': 9, 'user_is': 17},
        {'following': 13, 'user_is': 17},
        {'following': 14, 'user_is': 17},
        {'following': 15, 'user_is': 17},
        {'following': 16, 'user_is': 17},
        {'following': 1, 'user_is': 17},
        {'following': 4, 'user_is': 1},
        # {'following': 5, 'user_is': 1},
        # {'following': 6, 'user_is': 1},
        # {'following': 9, 'user_is': 1},
        # {'following': 13, 'user_is': 1},
        # {'following': 14, 'user_is': 1},
        # {'following': 15, 'user_is': 1},
        # {'following': 16, 'user_is': 1},
        {'following': 1, 'user_is': 2},
        {'following': 2, 'user_is': 1},
        {'following': 3, 'user_is': 4},
        {'following': 4, 'user_is': 3},
        {'following': 3, 'user_is': 5},
        {'following': 5, 'user_is': 3},
        {'following': 3, 'user_is': 6},
        {'following': 6, 'user_is': 3},
        # {'following': 8, 'user_is': 3},
        {'following': 4, 'user_is': 7},
        {'following': 7, 'user_is': 4},
        {'following': 4, 'user_is': 8},
        {'following': 8, 'user_is': 4},
        {'following': 5, 'user_is': 7},
        {'following': 7, 'user_is': 5},
        {'following': 5, 'user_is': 8},
        {'following': 8, 'user_is': 5},
        {'following': 6, 'user_is': 7},
        {'following': 7, 'user_is': 6},
        {'following': 6, 'user_is': 8},
        {'following': 8, 'user_is': 6},
        {'following': 9, 'user_is': 10},
        {'following': 10, 'user_is': 9},
        {'following': 9, 'user_is': 11},
        {'following': 11, 'user_is': 9},
        {'following': 12, 'user_is': 13},
        {'following': 13, 'user_is': 12}
    ]


    for friend in friends_list:
        user_is = friend['user_is']
        following = friend['following']

        relationship = insert(follows).values(user_is = user_is, following = following)
        db.session.execute(relationship)


    db.session.commit()


# Uses a raw SQL query to TRUNCATE or DELETE the users table. SQLAlchemy doesn't
# have a built in function to do this. With postgres in production TRUNCATE
# removes all the data from the table, and RESET IDENTITY resets the auto
# incrementing primary key, CASCADE deletes any dependent entities.  With
# sqlite3 in development you need to instead use DELETE to remove all data and
# it will reset the primary keys for you as well.
def undo_follows():
    if environment == "production":
        db.session.execute(f"TRUNCATE table {SCHEMA}.follows RESTART IDENTITY CASCADE;")
    else:
        db.session.execute(text("DELETE FROM follows"))

    db.session.commit()
